#!/bin/bash
if [[ ! -L ~/.ramdisk ]]; then
	echo -e "ramdisk is currently \033[0;31mDISABLED\033[0m"

elif [[ -L ~/.ramdisk && ! -e ~/.ramdisk ]]; then
	echo -e "ramdisk is currently \033[0;31mDISABLED\033[0m"
	rm ~/.ramdisk

else
	echo -e "ramdisk is currently \033[0;32mENABLED\033[0m"
	echo -e "\033[0;36m[\033[1;36mramdisk Properties\033[0;36m]\033[0m"
	echo
	df -h ~/.ramdisk
fi
