#!/bin/bash
if [ -z "$1" ]; then
	MAX_SIZE='8G'
else
	MAX_SIZE=$1
fi

sudo mkdir -p /dev/shm/ramdisk
if sudo mount -t tmpfs -o size="$MAX_SIZE" tmpfs /dev/shm/ramdisk; then
	ln -sf /dev/shm/ramdisk ~/.ramdisk
	echo -e "\033[1;32mSUCCESS\033[0m: ramdisk is enabled"
else
	sudo rm -rf /dev/shm/ramdisk
	if [[ -L ~/.ramdisk ]]; then
		rm ~/.ramdisk
	fi
fi


# Alternate Method:
# 	sudo modprobe brd rd_nr=1 rd_size=$((1024*1024))
# Preallocate
# 	sudo dd if=/dev/zero of=/dev/ram0 bs=1GiB status=progress
# Format to use
# 	sudo mkfs.ext4 /dev/ram0
# Finally mount
# 	sudo mkfs.ext4 /dev/ram0 
