#!/bin/bash

if [[ ! -d ~/.ramdisk ]]; then
	./create-ramdisk
fi

# Get intended file path
if [[ "$1" == /* ]]; then
	SYM_PATH=$1

else
	SYM_PATH=$PWD/$1
fi

echo "$SYM_PATH" >> /dev/shm/ramdisk/.symlinks	# make del easier
dir=/dev/shm/ramdisk/"${EPOCHREALTIME/[^0-9]/}"
mkdir $dir

ln -sf $dir $SYM_PATH
