#!/bin/bash

if [[ ! -d ~/.ramdisk ]]; then
	./create-ramdisk
fi

# Get intended file path
SYM_PATH=$(realpath "$1")

dir=/dev/shm/ramdisk/"${EPOCHREALTIME/[^0-9]/}"
mkdir $dir

# Make deleting symlinks created by this utility easier
cp /dev/shm/ramdisk/.symlinks "$dir/.symlinks"
echo "$SYM_PATH" >> "$dir/.symlinks"

# Atomically move the updated folder list to the main location
mv "$dir/.symlinks" "/dev/shm/ramdisk/.symlinks"

ln -sf $dir "$SYM_PATH"
